python run_benchmark.py  --config-name=benchmark_libero_goal \
            --multirun agents=goal_mamba_only_agent \
            agent_name=ddpm_mamba \
            group=ddpm_mamba_sweep_on_goal \
            hydra.launcher.name=m_sp_goal \
            obs_seq=1,5 \
            n_layers=12 \
            mamba_ssm_cfg.d_state=16,8 \
            mamba_ssm_cfg.d_conv=4,2 \
            seed=0,1,2