python run_benchmark.py  --config-name=benchmark_libero10 \
            --multirun agents=oc_ddpm_agent \
            agent_name=ddpm_encdec \
            task_suite=libero_10 \
            wandb.project=3_seed \
            group=ddpm_encdec \
            obs_seq=1,5 \
            diff_steps=16 \
            decoder_n_layer=6 \
            seed=0,1,2