python run_benchmark.py  --config-name=benchmark_libero_goal \
            --multirun agents=goal_mamba_cross_agent \
            agent_name=ddpm_mamba_cross \
            wandb.project=3_seed \
            group=ddpm_mamba_cross_goal \
            obs_seq=1,5 \
            mamba_encoder_cfg.d_state=16 \
            mamba_decoder_cfg.d_state=16 \
            enc_conv=4 \
            dec_conv=2 \
            seed=0,1,2