python run_benchmark.py  --config-name=benchmark_libero10 \
            --multirun agents=oc_ddpm_mamba_only_agent \
            agent_name=ddpm_mamba \
            task_suite=libero_10 \
            wandb.project=ablation \
            group=video \
            obs_seq=5 \
            n_layers=16 \
            mamba_ssm_cfg.d_state=16 \
            mamba_ssm_cfg.d_conv=4 \
            seed=0