python run_benchmark.py  --config-name=benchmark_libero_goal \
            --multirun agents=goal_mamba_only_agent \
            agent_name=ddpm_mamba \
            task_suite=libero_90 \
            group=libero_90_ddpm_mamba_goal \
            obs_seq=5 \
            train_batch_size=128 \
            n_layers=16 \
            mamba_ssm_cfg.d_state=16 \
            mamba_ssm_cfg.d_conv=4 \
            seed=0,1,2