python run_benchmark.py  --config-name=benchmark_libero_new \
            --multirun agents=bc_decoder \
            agent_name=bc_decoder \
            task_suite=libero_spatial,libero_object \
            wandb.project=3_seed \
            group=bc_decoder \
            obs_seq=1,5 \
            trans_n_layer=8 \
            seed=0,1,2