python run_benchmark.py  --config-name=benchmark_libero_goal \
            --multirun agents=goal_bc_mamba_cross \
            agent_name=bc_mamba_cross \
            task_suite=libero_goal,libero_90 \
            wandb.project=3_seed \
            group=bc_mamba_cross_goal \
            obs_seq=1,5 \
            n_layer_encoder=8 \
            seed=0,1,2